export type EmojiDef = { name: string; char: string; aliases?: string[] }

// Expanded curated emoji catalog for title autocomplete
// Includes common smileys, gestures, time, events, work/study, symbols, food/drink, travel, and nature.
export const EMOJIS: EmojiDef[] = [
  // Smileys & emotion
  { name: 'grinning', char: '😀', aliases: ['smiley'] },
  { name: 'smile', char: '😊', aliases: ['happy', 'blush'] },
  { name: 'laugh', char: '😂', aliases: ['joy', 'lol'] },
  { name: 'rofl', char: '🤣', aliases: ['rolling_laugh'] },
  { name: 'slight_smile', char: '🙂', aliases: ['smiley'] },
  { name: 'wink', char: '😉' },
  { name: 'thinking', char: '🤔' },
  { name: 'sunglasses', char: '😎', aliases: ['cool'] },
  { name: 'neutral', char: '😐', aliases: ['meh'] },
  { name: 'sad', char: '😞', aliases: ['frown'] },
  { name: 'cry', char: '😢', aliases: ['tears'] },
  { name: 'angry', char: '😠', aliases: ['mad'] },
  { name: 'mind_blown', char: '🤯', aliases: ['astonished'] },
  { name: 'sleeping', char: '😴', aliases: ['tired'] },
  { name: 'heart', char: '❤️', aliases: ['love'] },
  { name: 'sparkle_heart', char: '💖' },
  { name: 'blue_heart', char: '💙' },
  { name: 'green_heart', char: '💚' },
  { name: 'yellow_heart', char: '💛' },
  { name: 'purple_heart', char: '💜' },
  { name: 'broken_heart', char: '💔' },
  { name: 'star', char: '⭐' },
  { name: 'sparkles', char: '✨' },
  { name: 'fire', char: '🔥' },
  { name: 'tada', char: '🎉', aliases: ['party', 'confetti'] },
  { name: 'party', char: '🥳', aliases: ['celebrate'] },

  // Gestures & actions
  { name: 'clap', char: '👏' },
  { name: 'raised_hands', char: '🙌', aliases: ['hooray'] },
  { name: 'wave', char: '👋', aliases: ['hello', 'hi'] },
  { name: 'pray', char: '🙏', aliases: ['please', 'thanks'] },
  { name: 'muscle', char: '💪', aliases: ['strong'] },
  { name: 'thumbs_up', char: '👍', aliases: ['like', 'approve', 'yes'] },
  { name: 'thumbs_down', char: '👎', aliases: ['no'] },
  { name: 'point_right', char: '👉' },
  { name: 'point_left', char: '👈' },
  { name: 'point_up', char: '☝️' },
  { name: 'point_down', char: '👇' },

  // Time & scheduling
  { name: 'alarm', char: '⏰', aliases: ['clock'] },
  { name: 'timer', char: '⏲️', aliases: ['kitchen_timer'] },
  { name: 'stopwatch', char: '⏱️' },
  { name: 'hourglass', char: '⏳' },
  { name: 'calendar', char: '📅', aliases: ['date'] },
  { name: 'spiral_calendar', char: '🗓️', aliases: ['schedule'] },
  { name: 'memo', char: '📝', aliases: ['note'] },
  { name: 'pushpin', char: '📌', aliases: ['pin'] },

  // Work / study / tools
  { name: 'laptop', char: '💻', aliases: ['computer'] },
  { name: 'keyboard', char: '⌨️' },
  { name: 'gear', char: '⚙️', aliases: ['settings'] },
  { name: 'hammer_wrench', char: '🛠️', aliases: ['tools'] },
  { name: 'wrench', char: '🔧' },
  { name: 'hammer', char: '🔨' },
  { name: 'clipboard', char: '📋' },
  { name: 'chart_up', char: '📈', aliases: ['growth'] },
  { name: 'chart_down', char: '📉' },
  { name: 'trophy', char: '🏆', aliases: ['win', 'award'] },
  { name: 'medal', char: '🥇', aliases: ['gold'] },
  { name: 'book', char: '📘', aliases: ['study'] },
  { name: 'books', char: '📚' },
  { name: 'pencil', char: '✏️', aliases: ['edit'] },
  { name: 'magnifier', char: '🔎', aliases: ['search'] },
  { name: 'package', char: '📦', aliases: ['ship'] },
  { name: 'rocket', char: '🚀', aliases: ['launch', 'deploy', 'ship'] },
  { name: 'bug', char: '🐛' },
  { name: 'white_check_mark', char: '✅', aliases: ['check', 'done'] },
  { name: 'cross_mark', char: '❌', aliases: ['x'] },
  { name: 'warning', char: '⚠️', aliases: ['alert'] },

  // Arrows / symbols
  { name: 'arrow_right', char: '➡️' },
  { name: 'arrow_left', char: '⬅️' },
  { name: 'arrow_up', char: '⬆️' },
  { name: 'arrow_down', char: '⬇️' },
  { name: 'fast_forward', char: '⏩' },
  { name: 'rewind', char: '⏪' },
  { name: 'play', char: '▶️' },
  { name: 'pause', char: '⏸️' },
  { name: 'stop', char: '⏹️' },
  { name: 'repeat', char: '🔁' },

  // Activities / sports
  { name: 'soccer', char: '⚽' },
  { name: 'basketball', char: '🏀' },
  { name: 'tennis', char: '🎾' },
  { name: 'running', char: '🏃', aliases: ['run'] },
  { name: 'dumbbell', char: '🏋️', aliases: ['workout'] },

  // Food & drink
  { name: 'coffee', char: '☕' },
  { name: 'tea', char: '🍵' },
  { name: 'beer', char: '🍺' },
  { name: 'wine', char: '🍷' },
  { name: 'cocktail', char: '🍸' },
  { name: 'pizza', char: '🍕' },
  { name: 'burger', char: '🍔' },
  { name: 'fries', char: '🍟' },
  { name: 'cake', char: '🎂' },
  { name: 'candy', char: '🍬' },

  // Travel & places
  { name: 'house', char: '🏠', aliases: ['home'] },
  { name: 'office', char: '🏢' },
  { name: 'school', char: '🏫' },
  { name: 'factory', char: '🏭' },
  { name: 'airplane', char: '✈️', aliases: ['flight'] },
  { name: 'train', char: '🚆' },
  { name: 'car', char: '🚗' },

  // Music / media
  { name: 'musical_note', char: '🎵', aliases: ['music'] },
  { name: 'headphones', char: '🎧' },
  { name: 'microphone', char: '🎤' },

  // Nature & animals (selection)
  { name: 'dog', char: '🐶', aliases: ['dog_face'] },
  { name: 'cat', char: '🐱', aliases: ['cat_face'] },
  { name: 'rabbit', char: '🐰', aliases: ['bunny'] },
  { name: 'fox', char: '🦊', aliases: ['fox_face'] },
  { name: 'bear', char: '🐻' },
  { name: 'panda', char: '🐼' },
  { name: 'lion', char: '🦁' },
  { name: 'monkey', char: '🐵' },
  { name: 'unicorn', char: '🦄' },
  { name: 'owl', char: '🦉' },
  { name: 'butterfly', char: '🦋' },
  { name: 'lady_beetle', char: '🐞', aliases: ['ladybug'] },
  { name: 'honeybee', char: '🐝', aliases: ['bee'] },
  { name: 'snail', char: '🐌' },
  { name: 'crab', char: '🦀' },
  { name: 'octopus', char: '🐙' },
  { name: 'fish', char: '🐟' },
  { name: 'dolphin', char: '🐬' },
  { name: 'shark', char: '🦈' },

  // Weather / sky
  { name: 'sun', char: '☀️' },
  { name: 'moon', char: '🌙' },
  { name: 'cloud', char: '☁️' },
  { name: 'rain', char: '🌧️' },
  { name: 'snow', char: '❄️' },
  { name: 'rainbow', char: '🌈' },
  
  // Flags (popular selection)
  { name: 'flag_eu', char: '🇪🇺', aliases: ['eu', 'europe', 'european_union'] },
  { name: 'flag_us', char: '🇺🇸', aliases: ['us', 'usa', 'united_states', 'america'] },
  { name: 'flag_gb', char: '🇬🇧', aliases: ['uk', 'gb', 'britain', 'united_kingdom'] },
  { name: 'flag_fr', char: '🇫🇷', aliases: ['fr', 'france', 'french'] },
  { name: 'flag_de', char: '🇩🇪', aliases: ['de', 'germany', 'german'] },
  { name: 'flag_es', char: '🇪🇸', aliases: ['es', 'spain', 'spanish'] },
  { name: 'flag_it', char: '🇮🇹', aliases: ['it', 'italy', 'italian'] },
  { name: 'flag_pt', char: '🇵🇹', aliases: ['pt', 'portugal', 'portuguese'] },
  { name: 'flag_nl', char: '🇳🇱', aliases: ['nl', 'netherlands', 'dutch'] },
  { name: 'flag_be', char: '🇧🇪', aliases: ['be', 'belgium', 'belgian'] },
  { name: 'flag_ch', char: '🇨🇭', aliases: ['ch', 'switzerland', 'swiss'] },
  { name: 'flag_at', char: '🇦🇹', aliases: ['at', 'austria', 'austrian'] },
  { name: 'flag_se', char: '🇸🇪', aliases: ['se', 'sweden', 'swedish'] },
  { name: 'flag_no', char: '🇳🇴', aliases: ['no', 'norway', 'norwegian'] },
  { name: 'flag_dk', char: '🇩🇰', aliases: ['dk', 'denmark', 'danish'] },
  { name: 'flag_fi', char: '🇫🇮', aliases: ['fi', 'finland', 'finnish'] },
  { name: 'flag_ie', char: '🇮🇪', aliases: ['ie', 'ireland', 'irish'] },
  { name: 'flag_pl', char: '🇵🇱', aliases: ['pl', 'poland', 'polish'] },
  { name: 'flag_cz', char: '🇨🇿', aliases: ['cz', 'czech', 'czechia'] },
  { name: 'flag_sk', char: '🇸🇰', aliases: ['sk', 'slovakia', 'slovak'] },
  { name: 'flag_hu', char: '🇭🇺', aliases: ['hu', 'hungary', 'hungarian'] },
  { name: 'flag_ro', char: '🇷🇴', aliases: ['ro', 'romania', 'romanian'] },
  { name: 'flag_bg', char: '🇧🇬', aliases: ['bg', 'bulgaria', 'bulgarian'] },
  { name: 'flag_gr', char: '🇬🇷', aliases: ['gr', 'greece', 'greek'] },
  { name: 'flag_tr', char: '🇹🇷', aliases: ['tr', 'turkey', 'turkish'] },
  { name: 'flag_ua', char: '🇺🇦', aliases: ['ua', 'ukraine', 'ukrainian'] },
  { name: 'flag_ru', char: '🇷🇺', aliases: ['ru', 'russia', 'russian'] },
  { name: 'flag_il', char: '🇮🇱', aliases: ['il', 'israel', 'israeli'] },
  { name: 'flag_ae', char: '🇦🇪', aliases: ['ae', 'uae', 'united_arab_emirates'] },
  { name: 'flag_sa', char: '🇸🇦', aliases: ['sa', 'saudi', 'saudi_arabia'] },
  { name: 'flag_in', char: '🇮🇳', aliases: ['in', 'india', 'indian'] },
  { name: 'flag_cn', char: '🇨🇳', aliases: ['cn', 'china', 'chinese'] },
  { name: 'flag_jp', char: '🇯🇵', aliases: ['jp', 'japan', 'japanese'] },
  { name: 'flag_kr', char: '🇰🇷', aliases: ['kr', 'korea', 'south_korea', 'korean'] },
  { name: 'flag_tw', char: '🇹🇼', aliases: ['tw', 'taiwan', 'taiwanese'] },
  { name: 'flag_hk', char: '🇭🇰', aliases: ['hk', 'hong_kong'] },
  { name: 'flag_sg', char: '🇸🇬', aliases: ['sg', 'singapore', 'singaporean'] },
  { name: 'flag_au', char: '🇦🇺', aliases: ['au', 'australia', 'australian'] },
  { name: 'flag_nz', char: '🇳🇿', aliases: ['nz', 'new_zealand', 'kiwi'] },
  { name: 'flag_ca', char: '🇨🇦', aliases: ['ca', 'canada', 'canadian'] },
  { name: 'flag_br', char: '🇧🇷', aliases: ['br', 'brazil', 'brazilian'] },
  { name: 'flag_ar', char: '🇦🇷', aliases: ['ar', 'argentina', 'argentinian'] },
  { name: 'flag_mx', char: '🇲🇽', aliases: ['mx', 'mexico', 'mexican'] },
  { name: 'flag_cl', char: '🇨🇱', aliases: ['cl', 'chile', 'chilean'] },
  { name: 'flag_co', char: '🇨🇴', aliases: ['co', 'colombia', 'colombian'] },
  { name: 'flag_pe', char: '🇵🇪', aliases: ['pe', 'peru', 'peruvian'] },
  { name: 'flag_za', char: '🇿🇦', aliases: ['za', 'south_africa', 'south_african'] },
  { name: 'flag_ng', char: '🇳🇬', aliases: ['ng', 'nigeria', 'nigerian'] },
  { name: 'flag_ke', char: '🇰🇪', aliases: ['ke', 'kenya', 'kenyan'] },
  
  // Special flags
  { name: 'flag_rainbow', char: '🏳️‍🌈', aliases: ['pride', 'lgbt', 'rainbow_flag'] },
  { name: 'flag_transgender', char: '🏳️‍⚧️', aliases: ['trans', 'trans_flag'] },
  { name: 'flag_white', char: '🏳️', aliases: ['white_flag', 'surrender'] },
  { name: 'flag_black', char: '🏴', aliases: ['black_flag'] },
  { name: 'flag_pirate', char: '🏴‍☠️', aliases: ['pirate', 'jolly_roger'] },
  { name: 'checkered_flag', char: '🏁', aliases: ['finish', 'race'] },
]
