export type EmojiDef = { name: string; char: string; aliases?: string[] }

// Curated emoji catalog including common smileys, symbols, and animals
export const EMOJIS: EmojiDef[] = [
  // Smileys & people
  { name: 'grinning', char: '😀', aliases: ['smiley'] },
  { name: 'smile', char: '😊', aliases: ['happy', 'blush'] },
  { name: 'laugh', char: '😂', aliases: ['joy'] },
  { name: 'wink', char: '😉' },
  { name: 'thinking', char: '🤔' },
  { name: 'sunglasses', char: '😎', aliases: ['cool'] },
  { name: 'clap', char: '👏' },
  { name: 'thumbs_up', char: '👍', aliases: ['like', 'approve'] },
  { name: 'thumbs_down', char: '👎' },
  { name: 'heart', char: '❤️', aliases: ['love'] },
  { name: 'sparkle_heart', char: '💖' },
  { name: 'tada', char: '🎉', aliases: ['party'] },
  { name: 'party', char: '🥳', aliases: ['tada'] },
  { name: 'rocket', char: '🚀', aliases: ['launch'] },
  { name: 'fire', char: '🔥' },
  { name: 'sparkles', char: '✨' },
  { name: 'star', char: '⭐' },
  { name: 'check', char: '✅' },
  { name: 'x', char: '❌' },
  { name: 'warning', char: '⚠️' },
  { name: 'hourglass', char: '⏳' },
  { name: 'alarm', char: '⏰', aliases: ['clock'] },
  { name: 'bell', char: '🔔' },
  { name: 'musical_note', char: '🎵', aliases: ['music'] },
  { name: 'microphone', char: '🎤' },
  { name: 'laptop', char: '💻' },
  { name: 'coffee', char: '☕' },
  { name: 'pizza', char: '🍕' },

  // Animals & nature (expanded)
  { name: 'dog', char: '🐶', aliases: ['dog_face'] },
  { name: 'cat', char: '🐱', aliases: ['cat_face'] },
  { name: 'mouse', char: '🐭' },
  { name: 'hamster', char: '🐹' },
  { name: 'rabbit', char: '🐰', aliases: ['bunny'] },
  { name: 'fox', char: '🦊', aliases: ['fox_face'] },
  { name: 'bear', char: '🐻' },
  { name: 'panda', char: '🐼' },
  { name: 'koala', char: '🐨' },
  { name: 'tiger', char: '🐯' },
  { name: 'lion', char: '🦁' },
  { name: 'cow', char: '🐮' },
  { name: 'pig', char: '🐷', aliases: ['pig_face'] },
  { name: 'boar', char: '🐗' },
  { name: 'monkey', char: '🐵' },
  { name: 'monkey_face', char: '🐵' },
  { name: 'see_no_evil', char: '🙈' },
  { name: 'hear_no_evil', char: '🙉' },
  { name: 'speak_no_evil', char: '🙊' },
  { name: 'horse', char: '🐴' },
  { name: 'unicorn', char: '🦄' },
  { name: 'sheep', char: '🐑' },
  { name: 'goat', char: '🐐' },
  { name: 'camel', char: '🐫' },
  { name: 'llama', char: '🦙' },
  { name: 'giraffe', char: '🦒' },
  { name: 'elephant', char: '🐘' },
  { name: 'rhinoceros', char: '🦏', aliases: ['rhino'] },
  { name: 'hippopotamus', char: '🦛', aliases: ['hippo'] },
  { name: 'bison', char: '🦬' },
  { name: 'buffalo', char: '🐃', aliases: ['water_buffalo'] },
  { name: 'ox', char: '🐂' },
  { name: 'deer', char: '🦌' },
  { name: 'zebra', char: '🦓' },
  { name: 'kangaroo', char: '🦘' },
  { name: 'badger', char: '🦡' },
  { name: 'hedgehog', char: '🦔' },
  { name: 'bat', char: '🦇' },
  { name: 'owl', char: '🦉' },
  { name: 'eagle', char: '🦅' },
  { name: 'duck', char: '🦆' },
  { name: 'chicken', char: '🐔' },
  { name: 'rooster', char: '🐓' },
  { name: 'turkey', char: '🦃' },
  { name: 'bird', char: '🐦' },
  { name: 'penguin', char: '🐧' },
  { name: 'dove', char: '🕊️' },
  { name: 'butterfly', char: '🦋' },
  { name: 'bug', char: '🐛' },
  { name: 'ant', char: '🐜' },
  { name: 'honeybee', char: '🐝', aliases: ['bee'] },
  { name: 'beetle', char: '🪲' },
  { name: 'lady_beetle', char: '🐞', aliases: ['ladybug'] },
  { name: 'spider', char: '🕷️' },
  { name: 'scorpion', char: '🦂' },
  { name: 'snail', char: '🐌' },
  { name: 'butterfly', char: '🦋' },
  { name: 'crab', char: '🦀' },
  { name: 'lobster', char: '🦞' },
  { name: 'shrimp', char: '🦐' },
  { name: 'squid', char: '🦑' },
  { name: 'octopus', char: '🐙' },
  { name: 'fish', char: '🐟' },
  { name: 'tropical_fish', char: '🐠' },
  { name: 'blowfish', char: '🐡' },
  { name: 'dolphin', char: '🐬' },
  { name: 'whale', char: '🐳' },
  { name: 'shark', char: '🦈' },
  { name: 'crocodile', char: '🐊' },
  { name: 'turtle', char: '🐢' },
  { name: 'lizard', char: '🦎' },
  { name: 'snake', char: '🐍' },
  { name: 'dragon', char: '🐲' },
  { name: 'frog', char: '🐸' },

  // Weather/objects for variety
  { name: 'sun', char: '☀️' },
  { name: 'moon', char: '🌙' },
  { name: 'cloud', char: '☁️' },
  { name: 'rain', char: '🌧️' },
  { name: 'snow', char: '❄️' },
  { name: 'rainbow', char: '🌈' },
]

